

export const GET_EVENTS = "GET_EVENTS";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const GET_EVENT_DETAIL = "GET_EVENT_DETAIL";
export const GET_SUBCATEGORIES = "GET_SUBCATEGORIES";
export const ADD_EVENT_WISHLIST = "ADD_EVENT_WISHLIST ";
export const FILTER_CAT = "FILTER_CAT"; //Javi
export const FILTER_DATE = "FILTER_DATE";
export const FILTER_SUBCAT = "FILTER_SUBCAT";
export const FILTER_ADDRESS = "FILTER_ADDRESS";
export const ADD_EVENT = " ADD_EVENT";
export const UPDATE_EVENTS = "UPDATE_EVENTS";
export const UPDATE_USER_PASS = "UPDATE_USER_PASS";
export const SET_PAGE = "SET_PAGE"; //Javi
export const BULK_EVENTS = "BULK_EVENTS";
export const REMOVE_EVENT = "REMOVE_EVENT";
export const REMOVE_EVENT_WISHLIST = "REMOVE_EVENT_WISHLIST";
export const DELETE_EVENT = "DELETE_EVENT";
export const POST_USER = "POST_USER";
export const POST_TICKETS = "POST_TICKETS";
export const UPDATE_AVAILABLE = "UPDATE_AVAILABLE";
export const GET_TICKETS = "GET_TICKETS";
export const UPDATE_TICKET = "UPDATE_TICKET";
export const  USER_DATA = 'USER_DATA';
export const  USER_LOGOUT = 'USER_LOGOUT';
export const  USER_LOGOUT_GOOGLE = 'USER_LOGOUT_GOOGLE';
